server:
  port: 8761

# By default, the registry will also attempt to register itself, so youâ€™ll need to disable that, as well.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false